import * as XLSX from 'xlsx';
import type { Invoice } from '@/types';

export function exportToCSV(invoices: Invoice[], filename: string = 'invoices.csv') {
  if (invoices.length === 0) {
    alert('No invoices to export');
    return;
  }

  const headers = [
    'Invoice Number',
    'Vendor Name',
    'Total Amount',
    'Currency',
    'Invoice Date',
    'Due Date',
    'Status'
  ];

  const rows = invoices.map(inv => [
    inv.invoice_number,
    inv.vendor_name,
    inv.total_amount,
    inv.currency,
    inv.invoice_date,
    inv.due_date || 'N/A',
    inv.status
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => {
      const cellStr = String(cell);
      return cellStr.includes(',') ? `"${cellStr}"` : cellStr;
    }).join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToExcel(invoices: Invoice[], filename: string = 'invoices.xlsx') {
  if (invoices.length === 0) {
    alert('No invoices to export');
    return;
  }

  const data = invoices.map(inv => ({
    'Invoice Number': inv.invoice_number,
    'Vendor Name': inv.vendor_name,
    'Total Amount': inv.total_amount,
    'Currency': inv.currency,
    'Invoice Date': inv.invoice_date,
    'Due Date': inv.due_date || 'N/A',
    'Status': inv.status
  }));

  const worksheet = XLSX.utils.json_to_sheet(data);

  const columnWidths = [
    { wch: 20 },
    { wch: 25 },
    { wch: 15 },
    { wch: 10 },
    { wch: 15 },
    { wch: 15 },
    { wch: 10 }
  ];
  worksheet['!cols'] = columnWidths;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Invoices');

  XLSX.writeFile(workbook, filename);
}

export function exportToPDF(invoices: Invoice[], filename: string = 'invoices.pdf') {
  if (invoices.length === 0) {
    alert('No invoices to export');
    return;
  }

  let htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Invoices Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 20px;
        }
        h1 {
          color: #333;
          border-bottom: 2px solid #333;
          padding-bottom: 10px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background-color: #4CAF50;
          color: white;
        }
        tr:nth-child(even) {
          background-color: #f2f2f2;
        }
        .status-paid {
          color: #4CAF50;
          font-weight: bold;
        }
        .status-unpaid {
          color: #ff9800;
          font-weight: bold;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <h1>Invoices Report</h1>
      <p><strong>Generated on:</strong> ${new Date().toLocaleDateString()}</p>
      <p><strong>Total Invoices:</strong> ${invoices.length}</p>
      <table>
        <thead>
          <tr>
            <th>Invoice Number</th>
            <th>Vendor Name</th>
            <th>Amount</th>
            <th>Currency</th>
            <th>Invoice Date</th>
            <th>Due Date</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${invoices.map(inv => `
            <tr>
              <td>${inv.invoice_number}</td>
              <td>${inv.vendor_name}</td>
              <td>${inv.total_amount.toLocaleString()}</td>
              <td>${inv.currency}</td>
              <td>${new Date(inv.invoice_date).toLocaleDateString()}</td>
              <td>${inv.due_date ? new Date(inv.due_date).toLocaleDateString() : 'N/A'}</td>
              <td class="status-${inv.status}">${inv.status.toUpperCase()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      <div class="footer">
        <p>Report generated by Adamani AI RAG System</p>
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '', 'height=600,width=800');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.onload = function() {
      printWindow.print();
      printWindow.close();
    };
  } else {
    alert('Please allow popups to export PDF');
  }
}
